//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import Rswift
import UIKit

/// This `R` struct is generated and contains references to static resources.
struct R: Rswift.Validatable {
  fileprivate static let applicationLocale = hostingBundle.preferredLocalizations.first.flatMap { Locale(identifier: $0) } ?? Locale.current
  fileprivate static let hostingBundle = Bundle(for: R.Class.self)

  /// Find first language and bundle for which the table exists
  fileprivate static func localeBundle(tableName: String, preferredLanguages: [String]) -> (Foundation.Locale, Foundation.Bundle)? {
    // Filter preferredLanguages to localizations, use first locale
    var languages = preferredLanguages
      .map { Locale(identifier: $0) }
      .prefix(1)
      .flatMap { locale -> [String] in
        if hostingBundle.localizations.contains(locale.identifier) {
          if let language = locale.languageCode, hostingBundle.localizations.contains(language) {
            return [locale.identifier, language]
          } else {
            return [locale.identifier]
          }
        } else if let language = locale.languageCode, hostingBundle.localizations.contains(language) {
          return [language]
        } else {
          return []
        }
      }

    // If there's no languages, use development language as backstop
    if languages.isEmpty {
      if let developmentLocalization = hostingBundle.developmentLocalization {
        languages = [developmentLocalization]
      }
    } else {
      // Insert Base as second item (between locale identifier and languageCode)
      languages.insert("Base", at: 1)

      // Add development language as backstop
      if let developmentLocalization = hostingBundle.developmentLocalization {
        languages.append(developmentLocalization)
      }
    }

    // Find first language for which table exists
    // Note: key might not exist in chosen language (in that case, key will be shown)
    for language in languages {
      if let lproj = hostingBundle.url(forResource: language, withExtension: "lproj"),
         let lbundle = Bundle(url: lproj)
      {
        let strings = lbundle.url(forResource: tableName, withExtension: "strings")
        let stringsdict = lbundle.url(forResource: tableName, withExtension: "stringsdict")

        if strings != nil || stringsdict != nil {
          return (Locale(identifier: language), lbundle)
        }
      }
    }

    // If table is available in main bundle, don't look for localized resources
    let strings = hostingBundle.url(forResource: tableName, withExtension: "strings", subdirectory: nil, localization: nil)
    let stringsdict = hostingBundle.url(forResource: tableName, withExtension: "stringsdict", subdirectory: nil, localization: nil)

    if strings != nil || stringsdict != nil {
      return (applicationLocale, hostingBundle)
    }

    // If table is not found for requested languages, key will be shown
    return nil
  }

  /// Load string from Info.plist file
  fileprivate static func infoPlistString(path: [String], key: String) -> String? {
    var dict = hostingBundle.infoDictionary
    for step in path {
      guard let obj = dict?[step] as? [String: Any] else { return nil }
      dict = obj
    }
    return dict?[key] as? String
  }

  static func validate() throws {
    try font.validate()
    try intern.validate()
  }

  #if os(iOS) || os(tvOS)
  /// This `R.storyboard` struct is generated, and contains static references to 1 storyboards.
  struct storyboard {
    /// Storyboard `LaunchScreen`.
    static let launchScreen = _R.storyboard.launchScreen()

    #if os(iOS) || os(tvOS)
    /// `UIStoryboard(name: "LaunchScreen", bundle: ...)`
    static func launchScreen(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.launchScreen)
    }
    #endif

    fileprivate init() {}
  }
  #endif

  /// This `R.color` struct is generated, and contains static references to 22 colors.
  struct color {
    /// Color `AccentColor`.
    static let accentColor = Rswift.ColorResource(bundle: R.hostingBundle, name: "AccentColor")
    /// Color `accentDark`.
    static let accentDark = Rswift.ColorResource(bundle: R.hostingBundle, name: "accentDark")
    /// Color `accentFaded`.
    static let accentFaded = Rswift.ColorResource(bundle: R.hostingBundle, name: "accentFaded")
    /// Color `accentGreenLight`.
    static let accentGreenLight = Rswift.ColorResource(bundle: R.hostingBundle, name: "accentGreenLight")
    /// Color `accentGreen`.
    static let accentGreen = Rswift.ColorResource(bundle: R.hostingBundle, name: "accentGreen")
    /// Color `accentLight`.
    static let accentLight = Rswift.ColorResource(bundle: R.hostingBundle, name: "accentLight")
    /// Color `accentRedFaded`.
    static let accentRedFaded = Rswift.ColorResource(bundle: R.hostingBundle, name: "accentRedFaded")
    /// Color `accentRedLight`.
    static let accentRedLight = Rswift.ColorResource(bundle: R.hostingBundle, name: "accentRedLight")
    /// Color `accentRed`.
    static let accentRed = Rswift.ColorResource(bundle: R.hostingBundle, name: "accentRed")
    /// Color `accentYellowLight`.
    static let accentYellowLight = Rswift.ColorResource(bundle: R.hostingBundle, name: "accentYellowLight")
    /// Color `accentYellow`.
    static let accentYellow = Rswift.ColorResource(bundle: R.hostingBundle, name: "accentYellow")
    /// Color `accent`.
    static let accent = Rswift.ColorResource(bundle: R.hostingBundle, name: "accent")
    /// Color `baseBlack`.
    static let baseBlack = Rswift.ColorResource(bundle: R.hostingBundle, name: "baseBlack")
    /// Color `baseWhite`.
    static let baseWhite = Rswift.ColorResource(bundle: R.hostingBundle, name: "baseWhite")
    /// Color `blueLight`.
    static let blueLight = Rswift.ColorResource(bundle: R.hostingBundle, name: "blueLight")
    /// Color `expenseBtnColor`.
    static let expenseBtnColor = Rswift.ColorResource(bundle: R.hostingBundle, name: "expenseBtnColor")
    /// Color `incomeBtnColor`.
    static let incomeBtnColor = Rswift.ColorResource(bundle: R.hostingBundle, name: "incomeBtnColor")
    /// Color `shade1`.
    static let shade1 = Rswift.ColorResource(bundle: R.hostingBundle, name: "shade1")
    /// Color `shade2`.
    static let shade2 = Rswift.ColorResource(bundle: R.hostingBundle, name: "shade2")
    /// Color `shade3`.
    static let shade3 = Rswift.ColorResource(bundle: R.hostingBundle, name: "shade3")
    /// Color `shade4`.
    static let shade4 = Rswift.ColorResource(bundle: R.hostingBundle, name: "shade4")
    /// Color `zeroBlack`.
    static let zeroBlack = Rswift.ColorResource(bundle: R.hostingBundle, name: "zeroBlack")

    #if os(iOS) || os(tvOS)
    /// `UIColor(named: "AccentColor", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func accentColor(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.accentColor, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIColor(named: "accent", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func accent(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.accent, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIColor(named: "accentDark", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func accentDark(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.accentDark, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIColor(named: "accentFaded", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func accentFaded(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.accentFaded, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIColor(named: "accentGreen", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func accentGreen(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.accentGreen, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIColor(named: "accentGreenLight", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func accentGreenLight(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.accentGreenLight, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIColor(named: "accentLight", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func accentLight(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.accentLight, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIColor(named: "accentRed", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func accentRed(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.accentRed, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIColor(named: "accentRedFaded", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func accentRedFaded(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.accentRedFaded, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIColor(named: "accentRedLight", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func accentRedLight(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.accentRedLight, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIColor(named: "accentYellow", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func accentYellow(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.accentYellow, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIColor(named: "accentYellowLight", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func accentYellowLight(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.accentYellowLight, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIColor(named: "baseBlack", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func baseBlack(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.baseBlack, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIColor(named: "baseWhite", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func baseWhite(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.baseWhite, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIColor(named: "blueLight", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func blueLight(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.blueLight, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIColor(named: "expenseBtnColor", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func expenseBtnColor(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.expenseBtnColor, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIColor(named: "incomeBtnColor", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func incomeBtnColor(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.incomeBtnColor, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIColor(named: "shade1", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func shade1(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.shade1, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIColor(named: "shade2", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func shade2(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.shade2, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIColor(named: "shade3", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func shade3(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.shade3, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIColor(named: "shade4", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func shade4(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.shade4, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIColor(named: "zeroBlack", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func zeroBlack(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.zeroBlack, compatibleWith: traitCollection)
    }
    #endif

    #if os(watchOS)
    /// `UIColor(named: "AccentColor", bundle: ..., traitCollection: ...)`
    @available(watchOSApplicationExtension 4.0, *)
    static func accentColor(_: Void = ()) -> UIKit.UIColor? {
      return UIKit.UIColor(named: R.color.accentColor.name)
    }
    #endif

    #if os(watchOS)
    /// `UIColor(named: "accent", bundle: ..., traitCollection: ...)`
    @available(watchOSApplicationExtension 4.0, *)
    static func accent(_: Void = ()) -> UIKit.UIColor? {
      return UIKit.UIColor(named: R.color.accent.name)
    }
    #endif

    #if os(watchOS)
    /// `UIColor(named: "accentDark", bundle: ..., traitCollection: ...)`
    @available(watchOSApplicationExtension 4.0, *)
    static func accentDark(_: Void = ()) -> UIKit.UIColor? {
      return UIKit.UIColor(named: R.color.accentDark.name)
    }
    #endif

    #if os(watchOS)
    /// `UIColor(named: "accentFaded", bundle: ..., traitCollection: ...)`
    @available(watchOSApplicationExtension 4.0, *)
    static func accentFaded(_: Void = ()) -> UIKit.UIColor? {
      return UIKit.UIColor(named: R.color.accentFaded.name)
    }
    #endif

    #if os(watchOS)
    /// `UIColor(named: "accentGreen", bundle: ..., traitCollection: ...)`
    @available(watchOSApplicationExtension 4.0, *)
    static func accentGreen(_: Void = ()) -> UIKit.UIColor? {
      return UIKit.UIColor(named: R.color.accentGreen.name)
    }
    #endif

    #if os(watchOS)
    /// `UIColor(named: "accentGreenLight", bundle: ..., traitCollection: ...)`
    @available(watchOSApplicationExtension 4.0, *)
    static func accentGreenLight(_: Void = ()) -> UIKit.UIColor? {
      return UIKit.UIColor(named: R.color.accentGreenLight.name)
    }
    #endif

    #if os(watchOS)
    /// `UIColor(named: "accentLight", bundle: ..., traitCollection: ...)`
    @available(watchOSApplicationExtension 4.0, *)
    static func accentLight(_: Void = ()) -> UIKit.UIColor? {
      return UIKit.UIColor(named: R.color.accentLight.name)
    }
    #endif

    #if os(watchOS)
    /// `UIColor(named: "accentRed", bundle: ..., traitCollection: ...)`
    @available(watchOSApplicationExtension 4.0, *)
    static func accentRed(_: Void = ()) -> UIKit.UIColor? {
      return UIKit.UIColor(named: R.color.accentRed.name)
    }
    #endif

    #if os(watchOS)
    /// `UIColor(named: "accentRedFaded", bundle: ..., traitCollection: ...)`
    @available(watchOSApplicationExtension 4.0, *)
    static func accentRedFaded(_: Void = ()) -> UIKit.UIColor? {
      return UIKit.UIColor(named: R.color.accentRedFaded.name)
    }
    #endif

    #if os(watchOS)
    /// `UIColor(named: "accentRedLight", bundle: ..., traitCollection: ...)`
    @available(watchOSApplicationExtension 4.0, *)
    static func accentRedLight(_: Void = ()) -> UIKit.UIColor? {
      return UIKit.UIColor(named: R.color.accentRedLight.name)
    }
    #endif

    #if os(watchOS)
    /// `UIColor(named: "accentYellow", bundle: ..., traitCollection: ...)`
    @available(watchOSApplicationExtension 4.0, *)
    static func accentYellow(_: Void = ()) -> UIKit.UIColor? {
      return UIKit.UIColor(named: R.color.accentYellow.name)
    }
    #endif

    #if os(watchOS)
    /// `UIColor(named: "accentYellowLight", bundle: ..., traitCollection: ...)`
    @available(watchOSApplicationExtension 4.0, *)
    static func accentYellowLight(_: Void = ()) -> UIKit.UIColor? {
      return UIKit.UIColor(named: R.color.accentYellowLight.name)
    }
    #endif

    #if os(watchOS)
    /// `UIColor(named: "baseBlack", bundle: ..., traitCollection: ...)`
    @available(watchOSApplicationExtension 4.0, *)
    static func baseBlack(_: Void = ()) -> UIKit.UIColor? {
      return UIKit.UIColor(named: R.color.baseBlack.name)
    }
    #endif

    #if os(watchOS)
    /// `UIColor(named: "baseWhite", bundle: ..., traitCollection: ...)`
    @available(watchOSApplicationExtension 4.0, *)
    static func baseWhite(_: Void = ()) -> UIKit.UIColor? {
      return UIKit.UIColor(named: R.color.baseWhite.name)
    }
    #endif

    #if os(watchOS)
    /// `UIColor(named: "blueLight", bundle: ..., traitCollection: ...)`
    @available(watchOSApplicationExtension 4.0, *)
    static func blueLight(_: Void = ()) -> UIKit.UIColor? {
      return UIKit.UIColor(named: R.color.blueLight.name)
    }
    #endif

    #if os(watchOS)
    /// `UIColor(named: "expenseBtnColor", bundle: ..., traitCollection: ...)`
    @available(watchOSApplicationExtension 4.0, *)
    static func expenseBtnColor(_: Void = ()) -> UIKit.UIColor? {
      return UIKit.UIColor(named: R.color.expenseBtnColor.name)
    }
    #endif

    #if os(watchOS)
    /// `UIColor(named: "incomeBtnColor", bundle: ..., traitCollection: ...)`
    @available(watchOSApplicationExtension 4.0, *)
    static func incomeBtnColor(_: Void = ()) -> UIKit.UIColor? {
      return UIKit.UIColor(named: R.color.incomeBtnColor.name)
    }
    #endif

    #if os(watchOS)
    /// `UIColor(named: "shade1", bundle: ..., traitCollection: ...)`
    @available(watchOSApplicationExtension 4.0, *)
    static func shade1(_: Void = ()) -> UIKit.UIColor? {
      return UIKit.UIColor(named: R.color.shade1.name)
    }
    #endif

    #if os(watchOS)
    /// `UIColor(named: "shade2", bundle: ..., traitCollection: ...)`
    @available(watchOSApplicationExtension 4.0, *)
    static func shade2(_: Void = ()) -> UIKit.UIColor? {
      return UIKit.UIColor(named: R.color.shade2.name)
    }
    #endif

    #if os(watchOS)
    /// `UIColor(named: "shade3", bundle: ..., traitCollection: ...)`
    @available(watchOSApplicationExtension 4.0, *)
    static func shade3(_: Void = ()) -> UIKit.UIColor? {
      return UIKit.UIColor(named: R.color.shade3.name)
    }
    #endif

    #if os(watchOS)
    /// `UIColor(named: "shade4", bundle: ..., traitCollection: ...)`
    @available(watchOSApplicationExtension 4.0, *)
    static func shade4(_: Void = ()) -> UIKit.UIColor? {
      return UIKit.UIColor(named: R.color.shade4.name)
    }
    #endif

    #if os(watchOS)
    /// `UIColor(named: "zeroBlack", bundle: ..., traitCollection: ...)`
    @available(watchOSApplicationExtension 4.0, *)
    static func zeroBlack(_: Void = ()) -> UIKit.UIColor? {
      return UIKit.UIColor(named: R.color.zeroBlack.name)
    }
    #endif

    fileprivate init() {}
  }

  /// This `R.entitlements` struct is generated, and contains static references to 2 properties.
  struct entitlements {
    static let apsEnvironment = infoPlistString(path: [], key: "aps-environment") ?? "development"

    struct comAppleDeveloperApplesignin {
      static let `default` = infoPlistString(path: ["com.apple.developer.applesignin"], key: "Default") ?? "Default"

      fileprivate init() {}
    }

    fileprivate init() {}
  }

  /// This `R.file` struct is generated, and contains static references to 3 files.
  struct file {
    /// Resource file `GoogleService-Info.plist`.
    static let googleServiceInfoPlist = Rswift.FileResource(bundle: R.hostingBundle, name: "GoogleService-Info", pathExtension: "plist")
    /// Resource file `Manrope-ExtraBold.ttf`.
    static let manropeExtraBoldTtf = Rswift.FileResource(bundle: R.hostingBundle, name: "Manrope-ExtraBold", pathExtension: "ttf")
    /// Resource file `Manrope-Regular.ttf`.
    static let manropeRegularTtf = Rswift.FileResource(bundle: R.hostingBundle, name: "Manrope-Regular", pathExtension: "ttf")

    /// `bundle.url(forResource: "GoogleService-Info", withExtension: "plist")`
    static func googleServiceInfoPlist(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.googleServiceInfoPlist
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "Manrope-ExtraBold", withExtension: "ttf")`
    static func manropeExtraBoldTtf(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.manropeExtraBoldTtf
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "Manrope-Regular", withExtension: "ttf")`
    static func manropeRegularTtf(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.manropeRegularTtf
      return fileResource.bundle.url(forResource: fileResource)
    }

    fileprivate init() {}
  }

  /// This `R.font` struct is generated, and contains static references to 2 fonts.
  struct font: Rswift.Validatable {
    /// Font `Manrope-ExtraBold`.
    static let manropeExtraBold = Rswift.FontResource(fontName: "Manrope-ExtraBold")
    /// Font `Manrope-Regular`.
    static let manropeRegular = Rswift.FontResource(fontName: "Manrope-Regular")

    /// `UIFont(name: "Manrope-ExtraBold", size: ...)`
    static func manropeExtraBold(size: CGFloat) -> UIKit.UIFont? {
      return UIKit.UIFont(resource: manropeExtraBold, size: size)
    }

    /// `UIFont(name: "Manrope-Regular", size: ...)`
    static func manropeRegular(size: CGFloat) -> UIKit.UIFont? {
      return UIKit.UIFont(resource: manropeRegular, size: size)
    }

    static func validate() throws {
      if R.font.manropeExtraBold(size: 42) == nil { throw Rswift.ValidationError(description:"[R.swift] Font 'Manrope-ExtraBold' could not be loaded, is 'Manrope-ExtraBold.ttf' added to the UIAppFonts array in this targets Info.plist?") }
      if R.font.manropeRegular(size: 42) == nil { throw Rswift.ValidationError(description:"[R.swift] Font 'Manrope-Regular' could not be loaded, is 'Manrope-Regular.ttf' added to the UIAppFonts array in this targets Info.plist?") }
    }

    fileprivate init() {}
  }

  /// This `R.image` struct is generated, and contains static references to 13 images.
  struct image {
    /// Image `comma-button`.
    static let commaButton = Rswift.ImageResource(bundle: R.hostingBundle, name: "comma-button")
    /// Image `eight-button`.
    static let eightButton = Rswift.ImageResource(bundle: R.hostingBundle, name: "eight-button")
    /// Image `five-button`.
    static let fiveButton = Rswift.ImageResource(bundle: R.hostingBundle, name: "five-button")
    /// Image `four-button`.
    static let fourButton = Rswift.ImageResource(bundle: R.hostingBundle, name: "four-button")
    /// Image `green-arrow`.
    static let greenArrow = Rswift.ImageResource(bundle: R.hostingBundle, name: "green-arrow")
    /// Image `nine-button`.
    static let nineButton = Rswift.ImageResource(bundle: R.hostingBundle, name: "nine-button")
    /// Image `one-button`.
    static let oneButton = Rswift.ImageResource(bundle: R.hostingBundle, name: "one-button")
    /// Image `red-arrow`.
    static let redArrow = Rswift.ImageResource(bundle: R.hostingBundle, name: "red-arrow")
    /// Image `seven-button`.
    static let sevenButton = Rswift.ImageResource(bundle: R.hostingBundle, name: "seven-button")
    /// Image `six-button`.
    static let sixButton = Rswift.ImageResource(bundle: R.hostingBundle, name: "six-button")
    /// Image `three-button`.
    static let threeButton = Rswift.ImageResource(bundle: R.hostingBundle, name: "three-button")
    /// Image `two-button`.
    static let twoButton = Rswift.ImageResource(bundle: R.hostingBundle, name: "two-button")
    /// Image `zero-button`.
    static let zeroButton = Rswift.ImageResource(bundle: R.hostingBundle, name: "zero-button")

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "comma-button", bundle: ..., traitCollection: ...)`
    static func commaButton(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.commaButton, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "eight-button", bundle: ..., traitCollection: ...)`
    static func eightButton(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.eightButton, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "five-button", bundle: ..., traitCollection: ...)`
    static func fiveButton(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.fiveButton, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "four-button", bundle: ..., traitCollection: ...)`
    static func fourButton(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.fourButton, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "green-arrow", bundle: ..., traitCollection: ...)`
    static func greenArrow(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.greenArrow, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "nine-button", bundle: ..., traitCollection: ...)`
    static func nineButton(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.nineButton, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "one-button", bundle: ..., traitCollection: ...)`
    static func oneButton(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.oneButton, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "red-arrow", bundle: ..., traitCollection: ...)`
    static func redArrow(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.redArrow, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "seven-button", bundle: ..., traitCollection: ...)`
    static func sevenButton(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.sevenButton, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "six-button", bundle: ..., traitCollection: ...)`
    static func sixButton(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.sixButton, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "three-button", bundle: ..., traitCollection: ...)`
    static func threeButton(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.threeButton, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "two-button", bundle: ..., traitCollection: ...)`
    static func twoButton(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.twoButton, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "zero-button", bundle: ..., traitCollection: ...)`
    static func zeroButton(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.zeroButton, compatibleWith: traitCollection)
    }
    #endif

    fileprivate init() {}
  }

  /// This `R.info` struct is generated, and contains static references to 1 properties.
  struct info {
    struct uiApplicationSceneManifest {
      static let _key = "UIApplicationSceneManifest"
      static let uiApplicationSupportsMultipleScenes = false

      struct uiSceneConfigurations {
        static let _key = "UISceneConfigurations"

        struct uiWindowSceneSessionRoleApplication {
          struct defaultConfiguration {
            static let _key = "Default Configuration"
            static let uiSceneConfigurationName = infoPlistString(path: ["UIApplicationSceneManifest", "UISceneConfigurations", "UIWindowSceneSessionRoleApplication", "Default Configuration"], key: "UISceneConfigurationName") ?? "Default Configuration"
            static let uiSceneDelegateClassName = infoPlistString(path: ["UIApplicationSceneManifest", "UISceneConfigurations", "UIWindowSceneSessionRoleApplication", "Default Configuration"], key: "UISceneDelegateClassName") ?? "$(PRODUCT_MODULE_NAME).SceneDelegate"

            fileprivate init() {}
          }

          fileprivate init() {}
        }

        fileprivate init() {}
      }

      fileprivate init() {}
    }

    fileprivate init() {}
  }

  /// This `R.string` struct is generated, and contains static references to 6 localization tables.
  struct string {
    /// This `R.string.balance` struct is generated, and contains static references to 9 localization keys.
    struct balance {
      /// Value: EURO
      static let balanceCurrencyTypeEURO = Rswift.StringResource(key: "balance.currency.type.EURO", tableName: "Balance", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: RUB
      static let balanceCurrencyTypeRUB = Rswift.StringResource(key: "balance.currency.type.RUB", tableName: "Balance", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: USD
      static let balanceCurrencyTypeUSD = Rswift.StringResource(key: "balance.currency.type.USD", tableName: "Balance", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Баланс кошелька
      static let balanceViewWalletTotalTitle = Rswift.StringResource(key: "balance.view.wallet.total.title", tableName: "Balance", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Доход кошелька
      static let balanceViewWalletIncomeTitle = Rswift.StringResource(key: "balance.view.wallet.income.title", tableName: "Balance", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Общий баланс
      static let balanceViewWalletsTotalTitle = Rswift.StringResource(key: "balance.view.wallets.total.title", tableName: "Balance", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Общий доход
      static let balanceViewWalletsIncomeTitle = Rswift.StringResource(key: "balance.view.wallets.income.title", tableName: "Balance", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Общий расход
      static let balanceViewWalletsExpenseTitle = Rswift.StringResource(key: "balance.view.wallets.expense.title", tableName: "Balance", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Расход кошелька
      static let balanceViewWalletExpenseTitle = Rswift.StringResource(key: "balance.view.wallet.expense.title", tableName: "Balance", bundle: R.hostingBundle, locales: [], comment: nil)

      /// Value: EURO
      static func balanceCurrencyTypeEURO(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("balance.currency.type.EURO", tableName: "Balance", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Balance", preferredLanguages: preferredLanguages) else {
          return "balance.currency.type.EURO"
        }

        return NSLocalizedString("balance.currency.type.EURO", tableName: "Balance", bundle: bundle, comment: "")
      }

      /// Value: RUB
      static func balanceCurrencyTypeRUB(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("balance.currency.type.RUB", tableName: "Balance", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Balance", preferredLanguages: preferredLanguages) else {
          return "balance.currency.type.RUB"
        }

        return NSLocalizedString("balance.currency.type.RUB", tableName: "Balance", bundle: bundle, comment: "")
      }

      /// Value: USD
      static func balanceCurrencyTypeUSD(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("balance.currency.type.USD", tableName: "Balance", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Balance", preferredLanguages: preferredLanguages) else {
          return "balance.currency.type.USD"
        }

        return NSLocalizedString("balance.currency.type.USD", tableName: "Balance", bundle: bundle, comment: "")
      }

      /// Value: Баланс кошелька
      static func balanceViewWalletTotalTitle(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("balance.view.wallet.total.title", tableName: "Balance", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Balance", preferredLanguages: preferredLanguages) else {
          return "balance.view.wallet.total.title"
        }

        return NSLocalizedString("balance.view.wallet.total.title", tableName: "Balance", bundle: bundle, comment: "")
      }

      /// Value: Доход кошелька
      static func balanceViewWalletIncomeTitle(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("balance.view.wallet.income.title", tableName: "Balance", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Balance", preferredLanguages: preferredLanguages) else {
          return "balance.view.wallet.income.title"
        }

        return NSLocalizedString("balance.view.wallet.income.title", tableName: "Balance", bundle: bundle, comment: "")
      }

      /// Value: Общий баланс
      static func balanceViewWalletsTotalTitle(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("balance.view.wallets.total.title", tableName: "Balance", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Balance", preferredLanguages: preferredLanguages) else {
          return "balance.view.wallets.total.title"
        }

        return NSLocalizedString("balance.view.wallets.total.title", tableName: "Balance", bundle: bundle, comment: "")
      }

      /// Value: Общий доход
      static func balanceViewWalletsIncomeTitle(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("balance.view.wallets.income.title", tableName: "Balance", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Balance", preferredLanguages: preferredLanguages) else {
          return "balance.view.wallets.income.title"
        }

        return NSLocalizedString("balance.view.wallets.income.title", tableName: "Balance", bundle: bundle, comment: "")
      }

      /// Value: Общий расход
      static func balanceViewWalletsExpenseTitle(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("balance.view.wallets.expense.title", tableName: "Balance", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Balance", preferredLanguages: preferredLanguages) else {
          return "balance.view.wallets.expense.title"
        }

        return NSLocalizedString("balance.view.wallets.expense.title", tableName: "Balance", bundle: bundle, comment: "")
      }

      /// Value: Расход кошелька
      static func balanceViewWalletExpenseTitle(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("balance.view.wallet.expense.title", tableName: "Balance", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Balance", preferredLanguages: preferredLanguages) else {
          return "balance.view.wallet.expense.title"
        }

        return NSLocalizedString("balance.view.wallet.expense.title", tableName: "Balance", bundle: bundle, comment: "")
      }

      fileprivate init() {}
    }

    /// This `R.string.calculation` struct is generated, and contains static references to 10 localization keys.
    struct calculation {
      /// Value: 0
      static let calculationZero = Rswift.StringResource(key: "calculation.zero", tableName: "Calculation", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: 1
      static let calculationOne = Rswift.StringResource(key: "calculation.one", tableName: "Calculation", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: 2
      static let calculationTwo = Rswift.StringResource(key: "calculation.two", tableName: "Calculation", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: 3
      static let calculationThree = Rswift.StringResource(key: "calculation.three", tableName: "Calculation", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: 4
      static let calculationFour = Rswift.StringResource(key: "calculation.four", tableName: "Calculation", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: 5
      static let calculationFive = Rswift.StringResource(key: "calculation.five", tableName: "Calculation", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: 6
      static let calculationSix = Rswift.StringResource(key: "calculation.six", tableName: "Calculation", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: 7
      static let calculationSeven = Rswift.StringResource(key: "calculation.seven", tableName: "Calculation", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: 8
      static let calculationEight = Rswift.StringResource(key: "calculation.eight", tableName: "Calculation", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: 9
      static let calculationNine = Rswift.StringResource(key: "calculation.nine", tableName: "Calculation", bundle: R.hostingBundle, locales: [], comment: nil)

      /// Value: 0
      static func calculationZero(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("calculation.zero", tableName: "Calculation", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Calculation", preferredLanguages: preferredLanguages) else {
          return "calculation.zero"
        }

        return NSLocalizedString("calculation.zero", tableName: "Calculation", bundle: bundle, comment: "")
      }

      /// Value: 1
      static func calculationOne(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("calculation.one", tableName: "Calculation", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Calculation", preferredLanguages: preferredLanguages) else {
          return "calculation.one"
        }

        return NSLocalizedString("calculation.one", tableName: "Calculation", bundle: bundle, comment: "")
      }

      /// Value: 2
      static func calculationTwo(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("calculation.two", tableName: "Calculation", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Calculation", preferredLanguages: preferredLanguages) else {
          return "calculation.two"
        }

        return NSLocalizedString("calculation.two", tableName: "Calculation", bundle: bundle, comment: "")
      }

      /// Value: 3
      static func calculationThree(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("calculation.three", tableName: "Calculation", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Calculation", preferredLanguages: preferredLanguages) else {
          return "calculation.three"
        }

        return NSLocalizedString("calculation.three", tableName: "Calculation", bundle: bundle, comment: "")
      }

      /// Value: 4
      static func calculationFour(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("calculation.four", tableName: "Calculation", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Calculation", preferredLanguages: preferredLanguages) else {
          return "calculation.four"
        }

        return NSLocalizedString("calculation.four", tableName: "Calculation", bundle: bundle, comment: "")
      }

      /// Value: 5
      static func calculationFive(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("calculation.five", tableName: "Calculation", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Calculation", preferredLanguages: preferredLanguages) else {
          return "calculation.five"
        }

        return NSLocalizedString("calculation.five", tableName: "Calculation", bundle: bundle, comment: "")
      }

      /// Value: 6
      static func calculationSix(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("calculation.six", tableName: "Calculation", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Calculation", preferredLanguages: preferredLanguages) else {
          return "calculation.six"
        }

        return NSLocalizedString("calculation.six", tableName: "Calculation", bundle: bundle, comment: "")
      }

      /// Value: 7
      static func calculationSeven(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("calculation.seven", tableName: "Calculation", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Calculation", preferredLanguages: preferredLanguages) else {
          return "calculation.seven"
        }

        return NSLocalizedString("calculation.seven", tableName: "Calculation", bundle: bundle, comment: "")
      }

      /// Value: 8
      static func calculationEight(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("calculation.eight", tableName: "Calculation", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Calculation", preferredLanguages: preferredLanguages) else {
          return "calculation.eight"
        }

        return NSLocalizedString("calculation.eight", tableName: "Calculation", bundle: bundle, comment: "")
      }

      /// Value: 9
      static func calculationNine(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("calculation.nine", tableName: "Calculation", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Calculation", preferredLanguages: preferredLanguages) else {
          return "calculation.nine"
        }

        return NSLocalizedString("calculation.nine", tableName: "Calculation", bundle: bundle, comment: "")
      }

      fileprivate init() {}
    }

    /// This `R.string.createWallet` struct is generated, and contains static references to 8 localization keys.
    struct createWallet {
      /// Value: Баланс
      static let createWalletFormTitleBalance = Rswift.StringResource(key: "create.wallet.form.title.balance", tableName: "CreateWallet", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Валюта
      static let createWalletFormTitleCurrency = Rswift.StringResource(key: "create.wallet.form.title.currency", tableName: "CreateWallet", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Введите название кошелька
      static let createWalletFormPlaceholderName = Rswift.StringResource(key: "create.wallet.form.placeholder.name", tableName: "CreateWallet", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Выберите валюту
      static let createWalletFormPlaceholderCurrency = Rswift.StringResource(key: "create.wallet.form.placeholder.currency", tableName: "CreateWallet", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Изначальный баланс
      static let createWalletFormPlaceholderBalance = Rswift.StringResource(key: "create.wallet.form.placeholder.balance", tableName: "CreateWallet", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Название
      static let createWalletFormTitleName = Rswift.StringResource(key: "create.wallet.form.title.name", tableName: "CreateWallet", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Новый кошелек
      static let createWalletTitle = Rswift.StringResource(key: "create.wallet.title", tableName: "CreateWallet", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Создать кошелек
      static let createWalletButtonCreateTitle = Rswift.StringResource(key: "create.wallet.button.create.title", tableName: "CreateWallet", bundle: R.hostingBundle, locales: [], comment: nil)

      /// Value: Баланс
      static func createWalletFormTitleBalance(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("create.wallet.form.title.balance", tableName: "CreateWallet", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "CreateWallet", preferredLanguages: preferredLanguages) else {
          return "create.wallet.form.title.balance"
        }

        return NSLocalizedString("create.wallet.form.title.balance", tableName: "CreateWallet", bundle: bundle, comment: "")
      }

      /// Value: Валюта
      static func createWalletFormTitleCurrency(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("create.wallet.form.title.currency", tableName: "CreateWallet", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "CreateWallet", preferredLanguages: preferredLanguages) else {
          return "create.wallet.form.title.currency"
        }

        return NSLocalizedString("create.wallet.form.title.currency", tableName: "CreateWallet", bundle: bundle, comment: "")
      }

      /// Value: Введите название кошелька
      static func createWalletFormPlaceholderName(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("create.wallet.form.placeholder.name", tableName: "CreateWallet", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "CreateWallet", preferredLanguages: preferredLanguages) else {
          return "create.wallet.form.placeholder.name"
        }

        return NSLocalizedString("create.wallet.form.placeholder.name", tableName: "CreateWallet", bundle: bundle, comment: "")
      }

      /// Value: Выберите валюту
      static func createWalletFormPlaceholderCurrency(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("create.wallet.form.placeholder.currency", tableName: "CreateWallet", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "CreateWallet", preferredLanguages: preferredLanguages) else {
          return "create.wallet.form.placeholder.currency"
        }

        return NSLocalizedString("create.wallet.form.placeholder.currency", tableName: "CreateWallet", bundle: bundle, comment: "")
      }

      /// Value: Изначальный баланс
      static func createWalletFormPlaceholderBalance(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("create.wallet.form.placeholder.balance", tableName: "CreateWallet", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "CreateWallet", preferredLanguages: preferredLanguages) else {
          return "create.wallet.form.placeholder.balance"
        }

        return NSLocalizedString("create.wallet.form.placeholder.balance", tableName: "CreateWallet", bundle: bundle, comment: "")
      }

      /// Value: Название
      static func createWalletFormTitleName(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("create.wallet.form.title.name", tableName: "CreateWallet", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "CreateWallet", preferredLanguages: preferredLanguages) else {
          return "create.wallet.form.title.name"
        }

        return NSLocalizedString("create.wallet.form.title.name", tableName: "CreateWallet", bundle: bundle, comment: "")
      }

      /// Value: Новый кошелек
      static func createWalletTitle(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("create.wallet.title", tableName: "CreateWallet", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "CreateWallet", preferredLanguages: preferredLanguages) else {
          return "create.wallet.title"
        }

        return NSLocalizedString("create.wallet.title", tableName: "CreateWallet", bundle: bundle, comment: "")
      }

      /// Value: Создать кошелек
      static func createWalletButtonCreateTitle(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("create.wallet.button.create.title", tableName: "CreateWallet", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "CreateWallet", preferredLanguages: preferredLanguages) else {
          return "create.wallet.button.create.title"
        }

        return NSLocalizedString("create.wallet.button.create.title", tableName: "CreateWallet", bundle: bundle, comment: "")
      }

      fileprivate init() {}
    }

    /// This `R.string.profile` struct is generated, and contains static references to 3 localization keys.
    struct profile {
      /// Value: 
      static let profileTitle = Rswift.StringResource(key: "profile.title", tableName: "Profile", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Возможна авторизация через аккаунт Apple
      static let profileEmptyViewSubtitle = Rswift.StringResource(key: "profile.empty.view.subtitle", tableName: "Profile", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Вы не авторизованы
      static let profileEmptyViewTitle = Rswift.StringResource(key: "profile.empty.view.title", tableName: "Profile", bundle: R.hostingBundle, locales: [], comment: nil)

      /// Value: 
      static func profileTitle(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("profile.title", tableName: "Profile", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Profile", preferredLanguages: preferredLanguages) else {
          return "profile.title"
        }

        return NSLocalizedString("profile.title", tableName: "Profile", bundle: bundle, comment: "")
      }

      /// Value: Возможна авторизация через аккаунт Apple
      static func profileEmptyViewSubtitle(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("profile.empty.view.subtitle", tableName: "Profile", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Profile", preferredLanguages: preferredLanguages) else {
          return "profile.empty.view.subtitle"
        }

        return NSLocalizedString("profile.empty.view.subtitle", tableName: "Profile", bundle: bundle, comment: "")
      }

      /// Value: Вы не авторизованы
      static func profileEmptyViewTitle(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("profile.empty.view.title", tableName: "Profile", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Profile", preferredLanguages: preferredLanguages) else {
          return "profile.empty.view.title"
        }

        return NSLocalizedString("profile.empty.view.title", tableName: "Profile", bundle: bundle, comment: "")
      }

      fileprivate init() {}
    }

    /// This `R.string.walletDetail` struct is generated, and contains static references to 3 localization keys.
    struct walletDetail {
      /// Value: Доход
      static let walletDetailBottomBarIncomeTitle = Rswift.StringResource(key: "wallet.detail.bottom.bar.income.title", tableName: "WalletDetail", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Профиль
      static let walletDetailBottomBarProfileTitle = Rswift.StringResource(key: "wallet.detail.bottom.bar.profile.title", tableName: "WalletDetail", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Расход
      static let walletDetailBottomBarExpenseTitle = Rswift.StringResource(key: "wallet.detail.bottom.bar.expense.title", tableName: "WalletDetail", bundle: R.hostingBundle, locales: [], comment: nil)

      /// Value: Доход
      static func walletDetailBottomBarIncomeTitle(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("wallet.detail.bottom.bar.income.title", tableName: "WalletDetail", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "WalletDetail", preferredLanguages: preferredLanguages) else {
          return "wallet.detail.bottom.bar.income.title"
        }

        return NSLocalizedString("wallet.detail.bottom.bar.income.title", tableName: "WalletDetail", bundle: bundle, comment: "")
      }

      /// Value: Профиль
      static func walletDetailBottomBarProfileTitle(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("wallet.detail.bottom.bar.profile.title", tableName: "WalletDetail", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "WalletDetail", preferredLanguages: preferredLanguages) else {
          return "wallet.detail.bottom.bar.profile.title"
        }

        return NSLocalizedString("wallet.detail.bottom.bar.profile.title", tableName: "WalletDetail", bundle: bundle, comment: "")
      }

      /// Value: Расход
      static func walletDetailBottomBarExpenseTitle(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("wallet.detail.bottom.bar.expense.title", tableName: "WalletDetail", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "WalletDetail", preferredLanguages: preferredLanguages) else {
          return "wallet.detail.bottom.bar.expense.title"
        }

        return NSLocalizedString("wallet.detail.bottom.bar.expense.title", tableName: "WalletDetail", bundle: bundle, comment: "")
      }

      fileprivate init() {}
    }

    /// This `R.string.wallets` struct is generated, and contains static references to 3 localization keys.
    struct wallets {
      /// Value: Добавить кошелек
      static let walletsButtonAddTitle = Rswift.StringResource(key: "wallets.button.add.title", tableName: "Wallets", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Нет кошелька
      static let walletsEmptyViewTitle = Rswift.StringResource(key: "wallets.empty.view.title", tableName: "Wallets", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: У вас нет ни одого кошелька. Для работы приложения рекомендуется минимум один
      static let walletsEmptyViewSubtitle = Rswift.StringResource(key: "wallets.empty.view.subtitle", tableName: "Wallets", bundle: R.hostingBundle, locales: [], comment: nil)

      /// Value: Добавить кошелек
      static func walletsButtonAddTitle(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("wallets.button.add.title", tableName: "Wallets", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Wallets", preferredLanguages: preferredLanguages) else {
          return "wallets.button.add.title"
        }

        return NSLocalizedString("wallets.button.add.title", tableName: "Wallets", bundle: bundle, comment: "")
      }

      /// Value: Нет кошелька
      static func walletsEmptyViewTitle(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("wallets.empty.view.title", tableName: "Wallets", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Wallets", preferredLanguages: preferredLanguages) else {
          return "wallets.empty.view.title"
        }

        return NSLocalizedString("wallets.empty.view.title", tableName: "Wallets", bundle: bundle, comment: "")
      }

      /// Value: У вас нет ни одого кошелька. Для работы приложения рекомендуется минимум один
      static func walletsEmptyViewSubtitle(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("wallets.empty.view.subtitle", tableName: "Wallets", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Wallets", preferredLanguages: preferredLanguages) else {
          return "wallets.empty.view.subtitle"
        }

        return NSLocalizedString("wallets.empty.view.subtitle", tableName: "Wallets", bundle: bundle, comment: "")
      }

      fileprivate init() {}
    }

    fileprivate init() {}
  }

  fileprivate struct intern: Rswift.Validatable {
    fileprivate static func validate() throws {
      try _R.validate()
    }

    fileprivate init() {}
  }

  fileprivate class Class {}

  fileprivate init() {}
}

struct _R: Rswift.Validatable {
  static func validate() throws {
    #if os(iOS) || os(tvOS)
    try storyboard.validate()
    #endif
  }

  #if os(iOS) || os(tvOS)
  struct storyboard: Rswift.Validatable {
    static func validate() throws {
      #if os(iOS) || os(tvOS)
      try launchScreen.validate()
      #endif
    }

    #if os(iOS) || os(tvOS)
    struct launchScreen: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = UIKit.UIViewController

      let bundle = R.hostingBundle
      let name = "LaunchScreen"

      static func validate() throws {
        if #available(iOS 11.0, tvOS 11.0, *) {
        }
      }

      fileprivate init() {}
    }
    #endif

    fileprivate init() {}
  }
  #endif

  fileprivate init() {}
}
